### ISSUE TITLE
Only works once on rpi4

### ISSUE THREAD

**Issue by M1ngXU** [joshuarost/cleware-traffic-light#3]
Hi, while the cli-tool works on windows, my raspberry pi 4 can only execute this once after a reboot. The next times I just get errors, mostly timeout errors. Is there any fix to this?

**Comment by joshuarost** [comment]
Hi @M1ngXU, this tool has been written on a Linux Ubuntu machine and used on a Raspberry Pi 3. Therefor it should work. Have you added the [USB rule](https://github.com/joshrost/cleware-traffic-light#linux). Else, I would need more information on the errors.

**Comment by M1ngXU** [comment]
pretty sure that the usb rule was added, since i was able to turn it some lights on once. but until the next reboot the code just crashed with errors (i think some write errors)

**Comment by joshuarost** [comment]
Have you installed the package via pip or via this repository? You might want to install the current master until I'm able to update the pip package. Also, without the logs with the exact error, I unfortunately can't help you.

**Comment by M1ngXU** [comment]
ok :(
i mainly wrote your code in rust (resulting the same error), but iirc i was using the pip package. is there a known problem?

**Comment by joshuarost** [comment]
Ok strange. No, not that I know of. It just supports the new traffic light 4, and I don't know what type of model you have.

**Comment by M1ngXU** [comment]
hmm idk, but it worked fine on windows (also the pip version)

**Comment by joshuarost** [comment]
And it worked on my Raspberry Pi. I'm sorry, but like that, I can't help you.

**Comment by M1ngXU** [comment]
ok
