### ISSUE TITLE
New udev rule for USB-TischAmpel4

### ISSUE THREAD

**Issue by markus-meissner** [joshuarost/cleware-traffic-light#8]
Hi,

I'm using a USB-TischAmpel4 from 2023-10. This one seems to have a new product id:

```shell
$ sudo lsusb | grep Cleware
Bus 001 Device 002: ID 0d50:0030 Cleware GmbH Multiplexer
```

I'v change my udev rule accordingly. I think having two rules doesn't harm anything, so I would suggest to update the README.md to:

```
SUBSYSTEM=="usb", ATTR{idVendor}=="0d50", ATTR{idProduct}=="0008", MODE="660", GROUP="traffic-light"
SUBSYSTEM=="usb", ATTR{idVendor}=="0d50", ATTR{idProduct}=="0030", MODE="660", GROUP="traffic-light"
```

Thanks for maintaining cleware-traffic-light!

Kind regards Markus

**Comment by joshuarost** [comment]
I'm sorry for the late response. Thank you for the information. Done.
